repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.6.0'
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
    -   id: gitleaks
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: shellcheck
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1
    hooks:
    -   id: pylint

# Java code quality checks using Maven Checkstyle
-   repo: local
    hooks:
    -   id: checkstyle
        name: checkstyle (Java)
        entry: mvn
        args:
          - checkstyle:check
          - '-Dcheckstyle.config.location=scripts/lint/checkstyle.xml'
          - '-Dcheckstyle.failOnViolation=false'
          - '--no-transfer-progress'
          - '-q'
        language: system
        files: \.java$
        pass_filenames: false
        stages: [pre-push]
        exclude: |
            (?x)^(
                libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/.*|
                .*/target/.*
            )$
