# -----------------------------------------------------------------------------
# Copyright Siemens AG, 2016-2017.
# Copyright Bosch Software Innovations GmbH, 2017.
# Part of the SW360 Portal Project.
#
# All rights reserved. This configuration file is provided to you under the
# terms and conditions of the Eclipse Distribution License v1.0 which
# accompanies this distribution, and is available at
# http://www.eclipse.org/org/documents/edl-v10.php
#
# initial author: maximilian.huber@tngtech.com
# -----------------------------------------------------------------------------

sudo: required
dist: trusty
language: java
jdk: openjdk8
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.m2
    - /tmp/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y couchdb
  - sudo service couchdb restart
  - ./scripts/install-thrift.sh --no-cleanup
install: mvn dependency:resolve || true

env: MVN_ARGS="package"
script: mvn --fail-at-end $MVN_ARGS

matrix:
  include:
    - name: mvn package
      env: MVN_ARGS="package"
    - name: mvn validate
      env: MVN_ARGS="validate"
      before_install:
    - name: mvn pmd:pmd
      env: MVN_ARGS="pmd:pmd"
      before_install:
    - name: mvn dependency:analyze
      env: MVN_ARGS="dependency:analyze -DfailOnWarning"
      install: mvn package -DskipTests
    - name: check for license headers
      before_install: true
      install: true
      script: .travis/testForLicenseHeaders.sh
    # the following job sadly runs into timeout
    # - name: test docker install file
    #   before_install: true
    #   install: true
    #   script: scripts/compileWithDocker.sh
  allow_failures:
    - name: mvn dependency:analyze

