# Copyright BMW CarIT GmbH, 2021.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

services:
  sw360:
    image: "ghcr.io/eclipse-sw360/sw360:latest"
    restart: unless-stopped
    container_name: sw360
    depends_on:
      - couchdb
    ports:
      - "8080:8080"
      - "11311:11311"
    stdin_open: true
    tty: true
    volumes:
      - etc:/etc/sw360
      - ./config/sw360:/app/sw360/config

  couchdb:
    image: couchdb:3
    restart: unless-stopped
    environment:
      - COUCHDB_CREATE_DATABASE=yes
    ports:
      - "5984:5984"
    volumes:
      - couchdb:/opt/couchdb/data
      - ./config/couchdb/sw360_setup.ini:/opt/couchdb/etc/local.d/sw360_setup.ini:ro
      - ./config/couchdb/sw360_log.ini:/opt/couchdb/etc/local.d/sw360_log.ini:ro
      - ./logs/couchdb:/opt/couchdb/log
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://couchdb:5984/_up"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  couchdb: null
  etc: null

networks:
  default:
    name: sw360net
