# -----------------------------------------------------------------------------
# Copyright Helio Chissini de Castro 2022-2025
# Copyright Cariad SE 2024
# Part of the SW360 Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# -----------------------------------------------------------------------------

name: SW360 Thrift Resource Container

on:
  workflow_dispatch:
  push:
    paths:
      - 'third-party/thrift/Dockerfile'

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  THRIFT_VERSION: '0.20.0' # Will be override but post step. Kept it here for minimal version

jobs:
  thrift_image:
    name: Thrift Container
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout main repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Login to GitHub container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - name: Set up Docker build
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Get assigned Thrift version
        shell: bash
        run: |
          THRIFT_VERSION="$(cat third-party/thrift/version)"
          echo "THRIFT_VERSION=$THRIFT_VERSION" >> $GITHUB_ENV
          echo "Thrift is set to version $THRIFT_VERSION"

      - name: Extract components metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/thrift
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=snapshot
            type=semver,pattern={{version}}
            type=raw,value=${{ env.THRIFT_VERSION }}-noble
            type=raw,value=latest
            type=ref,event=tag
          labels: sw360,thrift

      - name: Build image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          load: false
          file: third-party/thrift/Dockerfile
          build-args: |
            THRIFT_VERSION=${{ env.THRIFT_VERSION }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
